# Generated by Django 2.2.6 on 2019-11-11 19:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128), size=None),
        ),
        migrations.AlterField(
            model_name='job',
            name='level',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('I', 'Internship'), ('E', 'Entry Level'), ('M', 'Mid Level'), ('S', 'Senior Level')], max_length=1), size=None),
        ),
    ]
