# Generated by Django 2.2.6 on 2019-11-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0002_auto_20191111_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='industry',
            new_name='industries',
        ),
    ]
