# Generated by Django 2.2.6 on 2019-11-11 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0003_auto_20191111_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='level',
            new_name='levels',
        ),
    ]
