# Generated by Django 2.2.6 on 2019-11-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0004_auto_20191111_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
