# Generated by Django 2.2.6 on 2019-11-11 20:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0005_auto_20191111_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='locations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128), blank=True, null=True, size=None),
        ),
    ]
