# Generated by Django 2.2.6 on 2019-11-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0006_job_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='locations',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
