# Generated by Django 2.2.6 on 2019-11-12 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0007_auto_20191112_0330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='locations',
            new_name='location',
        ),
    ]
